spring.application.name=demo

# Primary datasource -> your existing kalshi DB (used by JPA/Hibernate)
spring.datasource.url=jdbc:postgresql://localhost:5432/fightdb
spring.datasource.username=postgres
spring.datasource.password=postgres



# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.ai.vectorstore.pgvector.index-type=hnsw
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.dimensions=1536  

# Force schema initialization
spring.ai.vectorstore.pgvector.initialize-schema=true

# OpenAI (chat + embeddings)
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o-mini
spring.ai.openai.embedding.options.model=text-embedding-3-small

# SportsData API
sportsdata.mma.base-url=https://api.sportsdata.io/v3/mma
sportsdata.mma.api-key=${SPORTSDATA_API_KEY}

