spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/kalshi
spring.datasource.username=postgres
spring.datasource.password=12345

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o-mini

sportsdata.mma.base-url=https://api.sportsdata.io/v3/mma
sportsdata.mma.api-key=d9cbc3f6f3ee445a9812ac7fd9ba3026